services:
  jcow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jcow
    restart: unless-stopped
    volumes: 
      - ./:/var/www/html

    ports:
      - "8080:80"

    environment:
      TZ: Asia/Jakarta
      DISABLE_LEGACY_RECAPTCHA: 1
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: tls
      SMTP_USERNAME: ${SMTP_USERNAME:-ipanjabar933@gmail.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-moaluinmkghtvzyx}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-ipanjabar933@gmail.com}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME:-JCow}

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    container_name: jcow-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jcow
      MYSQL_USER: jcow
      MYSQL_PASSWORD: jcow

    volumes:
      - jcow-mysql-data:/var/lib/mysql

    command: 
      - --sql-mode=

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  jcow-mysql-data:
